#!perl

our $VERSION = '0.001';

use strict;
use warnings;

use Mojo::File qw(curfile);
use lib curfile->dirname->sibling('lib')->to_string;
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('FRDCSA::PlanMonitor');

=head1 NAME

plan_monitor - Plan Monitor based on Interactive Behavior Trees

=head1 DESCRIPTION

This software presently implements a barebones real-time web-based
interactive behavior tree plan monitor.

=head1 SYNOPSIS

This system will take recommendations (such as for instance the
CDC/WHO's guidelines related to the COVID-19 pandemic) compiled into a
behavior tree specification, an interactively walks people through
tasks most likely a mobile phone's web-browser.

Eventually, the user will be able to enter into the interface a task
such as 'go to the grocery store' and the corresponding procedure wll
be found.  The user will then be walked through this procedure, like
an interactive checklist that can branch based on results of tasks.

Currently, there is a default behavior tree specified in the Users
model, which the user will be walked through.  We are working to
expand the kinds of behavior tree nodes available, the loading and
context switching mechanism, etc.

We are releasing early and often in order to successfully release this
system.  It is part of the FRDCSA (https://frdcsa.org), but designed
to be independent of any existing (unreleased) FRDCSA libraries to
make it easier to install.

=head1 AUTHOR

Andrew John Dougherty

=head1 LICENSE

GPLv3

=head1 INSTALLATION

Using C<cpan>:

    $ cpan FRDCSA::PlanMonitor

Manual install:

    $ perl Makefile.PL
    $ make
    $ make install

=cut
